version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password # Ganti dengan password yang kuat
      MYSQL_DATABASE: acara_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password # Ganti dengan password yang kuat
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: